apiVersion: nvcf.nvidia.com/v1alpha1
kind: ModelDeployment
metadata:
  name: tets
  namespace: models-staging
  annotations:
    backstage.io/created-by: 
    backstage.io/created-at: "${{ '' | now }}"
spec:
  image: nvcr.io/myorg/models/my-model:v1.0.0
  tensorParallelism: 1
  instanceType: H100_1x
  replicas: 1
  maxConcurrency: 10
  health:
    uri: /health
    protocol: HTTP
    port: 8000